# Generated by Django 5.1.1 on 2025-10-26 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("Extract", "Extract"),
                            ("Transform", "Transform"),
                            ("Train", "Train"),
                            ("Predict", "Predict"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("status", models.CharField(default="idle", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inputs",
                    models.ManyToManyField(
                        blank=True, related_name="outputs", to="pipeline.node"
                    ),
                ),
            ],
        ),
    ]
