# Generated by Django 5.1.1 on 2025-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="node_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
