# Generated by Django 5.1.1 on 2025-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_node_node_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
